### ISSUE TITLE
numozart can not find method test_rnnrbm() help

### ISSUE THREAD

**Issue by DefinitlyEvil** [nupic-community/nupic.audio#19]
I am using the latest version of nupic, but it gave me that error! please help! Thanks so much.

**Comment by rhyolight** [comment]
@passiweinberger

**Comment by passiweinberger** [comment]
It's not done yet :/ 
I have it somewhat working with a recurrent Bolzman-Net but did not push it as it does not really have too much to do with nupic... 
@rhyolight Sould it though? To have a at least somewhat working version online? 

This is still on my TODO but i am lacking free time in the moment. .. :(

**Comment by passiweinberger** [comment]
I put the RNN-RBM implementation in [here](https://github.com/nupic-community/nupic.audio/blob/master/NuMozart/NuMozart_RNNRBM.py)

As I said, If you like the idea, most utils are there and working, so having a HTM learn and generate sequences shouldn't be a huge step from there :) I just don't find time atm...

**Comment by DefinitlyEvil** [comment]
@passiweinberger Thanks so much!

**Comment by DefinitlyEvil** [comment]
And I am a Nupic noob. xD

**Comment by passiweinberger** [comment]
You're welcome :) We all are in the beginning ;) 

Feel free to get back to me if you're interested in getting this project going :)

**Comment by DefinitlyEvil** [comment]
@passiweinberger I will. )
